name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node environment
        uses: actions/setup-node@v2

      - name: Install packages
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Unit test
        run: npm run test